name: SQLite / Release

on:
  push:
    # On Push to Master branch
    branches:
      - master
    # Ignore all Tags / Release
    tags-ignore:
      - '**'

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.nuget }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            nuget:
              - '**.nuspec'

  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Package Version
        uses: KinsonDigital/VersionMiner@v1.0.0
        id: get-version
        with:
          repo-owner: Mediaportal-Plugin-Team
          repo-name: SQLite
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: master
          file-format: xml
          file-path: "SQLite/Sqlite.nuspec"
          version-keys: version
          fail-when-version-not-found: false

  release:
    name: Release
    needs:
      - changes
      - version
    permissions:
      contents: write
    if: ${{ needs.changes.outputs.changes == 'true' && needs.version.outputs.version }}

    runs-on: windows-2022

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pack
        run: nuget.exe pack Sqlite.nuspec
        working-directory: ${{ github.workspace }}\SQLite

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: SQLite ${{ needs.version.outputs.version }}
          tag_name: ${{ needs.version.outputs.version }}
          generate_release_notes: true
          files: |
            SQLite/*.nupkg

  ci-status:
    name: Status
    runs-on: ubuntu-latest
    needs:
      - release
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
